const data = [
  { description: "Air coming from the vents is warm, even when the thermostat is set to cool.", skills: ["air conditioning"] },
  { description: "Bathroom exhaust fan is noisy and not removing moisture effectively.", skills: ["ventilation"] },
  { description: "Boiler pressure keeps dropping and needs frequent repressurization.", skills: ["boiler repair"] },
  { description: "Buzzing sound coming from the electrical panel.", skills: ["circuit repair"] },
  { description: "Carpet in the bedrooms is worn out and needs replacement.", skills: ["flooring installation"] },
  { description: "Circuit breaker trips whenever the microwave and toaster are used simultaneously.", skills: ["circuit repair"] },
  { description: "Cracks appearing along the ceiling and wall joints.", skills: ["drywall repair"] },
  { description: "Existing cabinet doors are warped and need replacement.", skills: ["cabinet making"] },
  { description: "Freezer is accumulating frost too quickly and needs defrosting.", skills: ["refrigeration"] },
  { description: "Furnace is making a loud banging noise when it starts up.", skills: ["heating systems"] },
  { description: "Garbage disposal is jammed and making a humming noise.", skills: ["plumbing"] },
  { description: "Hissing sound coming from behind the toilet.", skills: ["leak repair"] },
  { description: "Ice maker in the freezer has stopped working.", skills: ["refrigeration"] },
  { description: "Intermittent power outages in specific rooms of the house.", skills: ["circuit repair"] },
  { description: "Kitchen island needs new drawer fronts and hardware installed.", skills: ["cabinet making"] },
  { description: "Kitchen range hood is not drawing out cooking odors.", skills: ["ventilation"] },
  { description: "Large hole in the living room wall from a door handle impact.", skills: ["drywall repair"] },
  { description: "Lights flicker throughout the house when large appliances turn on.", skills: ["electrical"] },
  { description: "Low water pressure throughout the entire house.", skills: ["plumbing"] },
  { description: "Need a complete ductwork cleaning and inspection.", skills: ["hvac"] },
  { description: "Need a custom-built pergola for the backyard patio.", skills: ["carpentry"] },
  { description: "Need a larger capacity water heater to meet household demands.", skills: ["water heater installation"] },
  { description: "Need a new water heater installed in the garage.", skills: ["water heater installation", "plumbing"] },
  { description: "Need custom cabinets built for an oddly-shaped kitchen corner.", skills: ["cabinet making"] },
  { description: "Need new energy-efficient fixtures throughout the house.", skills: ["lighting installation"] },
  { description: "Need new kitchen cabinets installed and old ones removed.", skills: ["cabinet making", "carpentry"] },
  { description: "Need to extend gas line for an outdoor grill installation.", skills: ["pipe fitting"] },
  { description: "Need to fix peeling paint in the bathroom and repaint.", skills: ["painting"] },
  { description: "Need to install a whole-house ventilation system for better air quality.", skills: ["ventilation"] },
  { description: "Need to install wiring for a hot tub in the backyard.", skills: ["wiring"] },
  { description: "Need to patch up multiple small holes from removed wall anchors.", skills: ["drywall repair"] },
  { description: "Need to replace water-damaged hardwood floors in the dining room.", skills: ["flooring installation"] },
  { description: "Need to reroute pipes to accommodate a kitchen island installation.", skills: ["pipe fitting"] },
  { description: "Need to rewire an old house with outdated knob-and-tube wiring.", skills: ["wiring"] },
  { description: "Need to upgrade the electrical panel to accommodate new appliances.", skills: ["electrical"] },
  { description: "Outlet sparks when plugging in appliances.", skills: ["circuit repair"] },
  { description: "Pilot light on the boiler keeps going out.", skills: ["boiler repair"] },
  { description: "Pipes in the basement are making loud banging noises.", skills: ["pipe fitting"] },
  { description: "Puddle forming under the kitchen sink whenever it's used.", skills: ["leak repair"] },
  { description: "Water under the kitchen sink whenever it's used.", skills: ["leak repair"] },
  { description: "Radiators are cold at the top but hot at the bottom.", skills: ["boiler repair"] },
  { description: "Refrigerator is not cooling properly and making a buzzing sound.", skills: ["refrigeration"] },
  { description: "Renovating the entire kitchen, including new cabinets, countertops, and appliance installations.", skills: ["cabinet making", "carpentry", "electrical", "plumbing"] },
  { description: "Several outlets in the kitchen are not working.", skills: ["electrical"] },
  { description: "Sewer line backup causing multiple drains to gurgle and smell.", skills: ["plumbing"] },
  { description: "Some rooms are much colder than others when the heat is on.", skills: ["heating systems"] },
  { description: "Strange odor coming from the air conditioner when it's running.", skills: ["air conditioning"] },
  { description: "Strange smells coming from the vents when the system is running.", skills: ["hvac"] },
  { description: "The AC unit is making a loud buzzing noise and not cooling effectively.", skills: ["air conditioning"] },
  { description: "The air conditioner is blowing warm air and making strange noises.", skills: ["air conditioning", "hvac"] },
  { description: "The air conditioner is not cooling properly", skills: ["HVAC", "cooling system"] },
  { description: "The attic is poorly ventilated, causing excessive heat buildup.", skills: ["ventilation"] },
  { description: "The attic needs additional insulation to improve energy efficiency.", skills: ["insulation", "energy efficiency"] },
  { description: "The basement flooded due to a pipe burst, requiring extensive repairs.", skills: ["plumbing", "leak repair", "drywall repair", "flooring installation"] },
  { description: "The basement walls are damp and showing signs of mold growth.", skills: ["waterproofing", "mold remediation"] },
  { description: "The bathroom door handle is loose and needs tightening", skills: ["carpentry", "hardware repair"] },
  { description: "The bathroom exhaust fan is noisy and not venting properly.", skills: ["ventilation", "electrical"] },
  { description: "The bathroom needs new light fixtures installed.", skills: ["lighting installation", "electrical"] },
  { description: "The bathtub faucet is dripping constantly and needs to be fixed.", skills: ["plumbing", "leak repair"] },
  { description: "The bedroom walls have crayon marks and need repainting.", skills: ["painting"] },
  { description: "The boiler is leaking and not heating the water properly.", skills: ["boiler repair", "leak repair", "heating systems"] },
  { description: "The boiler is making knocking sounds and not producing hot water.", skills: ["boiler repair"] },
  { description: "The built-in microwave is not heating food and the turntable is not spinning.", skills: ["appliance repair", "electrical"] },
  { description: "The ceiling fan in the living room is wobbling and making noise.", skills: ["electrical", "ceiling fan installation"] },
  { description: "The central heating system is not distributing heat evenly throughout the house.", skills: ["heating systems", "hvac"] },
  { description: "The chandelier in the dining room is outdated and needs replacement.", skills: ["lighting installation"] },
  { description: "The chimney is blocked and needs cleaning to prevent smoke backflow.", skills: ["chimney cleaning", "fireplace maintenance"] },
  { description: "The circuit breaker keeps tripping when using multiple appliances.", skills: ["circuit repair", "electrical"] },
  { description: "The current water heater is old and needs replacement.", skills: ["water heater installation"] },
  { description: "The dimmer switches in the dining room are not working properly.", skills: ["wiring"] },
  { description: "The dishwasher is leaking and leaving puddles on the kitchen floor.", skills: ["appliance repair", "plumbing"] },
  { description: "The driveway has large cracks and needs to be resurfaced.", skills: ["concrete work", "paving"] },
  { description: "The electric stove burners are not heating evenly and need repair.", skills: ["appliance repair", "electrical"] },
  { description: "The electrical outlets in the bedroom are not working.", skills: ["electrical", "wiring"] },
  { description: "The entire interior of the house needs to be repainted.", skills: ["painting"] },
  { description: "The exterior of the house needs a fresh coat of paint.", skills: ["painting"] },
  { description: "The front door lock is sticking and difficult to open.", skills: ["locksmith", "door repair"] },
  { description: "The front porch railing is loose and needs reinforcement.", skills: ["carpentry"] },
  { description: "The furnace is making a loud banging noise when it starts up.", skills: ["hvac", "heating systems"] },
  { description: "The garage door opener is not working and needs to be replaced.", skills: ["garage door repair", "electrical"] },
  { description: "The gutters are clogged and overflowing, causing water damage to the foundation.", skills: ["gutter cleaning", "exterior maintenance"] },
  { description: "The hardwood flooring in the dining room is warped and needs replacement.", skills: ["flooring installation", "carpentry"] },
  { description: "The heating system cycles on and off too frequently.", skills: ["heating systems"] },
  { description: "The HVAC system is not maintaining consistent temperature throughout the house.", skills: ["hvac"] },
  { description: "The HVAC system needs a complete overhaul, including ductwork repair.", skills: ["hvac", "air conditioning", "heating systems", "ventilation"] },
  { description: "The indoor AC unit is leaking water onto the floor.", skills: ["air conditioning"] },
  { description: "The kitchen sink garbage disposal is jammed and won't turn on.", skills: ["plumbing", "appliance repair"] },
  { description: "The kitchen sink is leaking and water is pooling on the floor", skills: ["plumbing", "leak repair"] },
  { description: "The living room walls have cracks that need to be repaired and painted.", skills: ["drywall repair", "painting"] },
  { description: "The outdoor HVAC unit is making excessive noise.", skills: ["hvac"] },
  { description: "The outdoor security lights need to be rewired and replaced.", skills: ["wiring", "lighting installation", "electrical"] },
  { description: "The pipes in the basement are making loud noises and need inspection.", skills: ["pipe fitting", "plumbing"] },
  { description: "The pool pump is making strange noises and not circulating water effectively.", skills: ["pool maintenance", "pump repair"] },
  { description: "The refrigerator is not cooling properly and making a buzzing sound.", skills: ["refrigeration", "appliance repair"] },
  { description: "The roof is leaking in multiple spots after heavy rain.", skills: ["roofing", "leak repair"] },
  { description: "The sliding glass door to the patio is off its track and won't close properly.", skills: ["door repair", "glass installation"] },
  { description: "The sprinkler system in the yard is leaking and needs adjustment.", skills: ["irrigation", "landscaping", "plumbing"] },
  { description: "The staircase handrail is loose and needs to be secured.", skills: ["carpentry", "safety repairs"] },
  { description: "The sump pump in the basement is not working, risking flooding.", skills: ["plumbing", "pump repair", "flood prevention"] },
  { description: "The thermostat is not responding and the HVAC system won't turn on.", skills: ["hvac", "electrical", "thermostat installation"] },
  { description: "The tile flooring in the bathroom is cracked and needs replacement.", skills: ["flooring installation"] },
  { description: "The toilet is constantly running and needs repair.", skills: ["plumbing"] },
  { description: "The toilet is constantly running and won't stop filling.", skills: ["plumbing"] },
  { description: "The ventilation system in the attic is not working efficiently.", skills: ["ventilation", "hvac"] },
  { description: "The vinyl siding on the exterior of the house is cracked and falling off.", skills: ["siding repair", "exterior maintenance"] },
  { description: "The water heater is leaking and needs immediate replacement.", skills: ["water heater installation"] },
  { description: "The water pressure throughout the house is low and needs to be addressed.", skills: ["plumbing", "pump repair"] },
  { description: "The windows in the bedroom are drafty and need to be resealed or replaced.", skills: ["window installation", "insulation"] },
  { description: "The wooden deck in the backyard is rotting and needs replacement.", skills: ["carpentry", "deck building"] },
  { description: "The wooden fence in the backyard is leaning and several posts need replacement.", skills: ["fence repair", "carpentry"] },
  { description: "The wooden stairs are creaking and feel unstable.", skills: ["carpentry"] },
  { description: "There's a large hole in the living room wall that needs repair.", skills: ["drywall repair", "painting"] },
  { description: "There's a strong sewage smell coming from the bathroom drains.", skills: ["plumbing", "drain cleaning"] },
  { description: "There's a water leak under the kitchen sink that needs to be fixed.", skills: ["leak repair", "plumbing"] },
  { description: "Tiles in the bathroom are cracked and coming loose.", skills: ["flooring installation"] },
  { description: "Want to add a built-in bookshelf to the living room.", skills: ["cabinet making"] },
  { description: "Want to add more outlets in the home office for computer equipment.", skills: ["wiring"] },
  { description: "Want to add motion-sensor lights to the exterior of the house.", skills: ["lighting installation"] },
  { description: "Want to convert from oil heating to a natural gas system.", skills: ["heating systems"] },
  { description: "Want to install crown molding in the dining room.", skills: ["carpentry"] },
  { description: "Want to install luxury vinyl tile in the basement.", skills: ["flooring installation"] },
  { description: "Want to install outdoor lighting and outlets on the patio.", skills: ["electrical"] },
  { description: "Want to install recessed lighting in the living room.", skills: ["lighting installation"] },
  { description: "Want to repaint the kitchen cabinets for a updated look.", skills: ["painting"] },
  { description: "Want to replace old galvanized pipes with modern PEX piping.", skills: ["pipe fitting"] },
  { description: "Want to upgrade to a tankless water heater for energy efficiency.", skills: ["water heater installation"] },
  { description: "Water damage has caused the drywall to bubble and peel in the bathroom.", skills: ["drywall repair"] },
  { description: "Water dispenser on the fridge door is leaking.", skills: ["refrigeration"] },
  { description: "Water stain on the ceiling below the upstairs bathroom.", skills: ["leak repair"] },
  { description: "Wet spots appearing on the basement walls after heavy rain.", skills: ["leak repair"] },
  { description: "Central air conditioning unit not cooling properly.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler is making strange noises and not heating water.", skills: ["boiler repair", "heating systems"] },
  { description: "Custom kitchen cabinets needed for a remodel.", skills: ["cabinet making", "carpentry"] },
  { description: "Repair a broken light switch in the living room.", skills: ["electrical", "circuit repair"] },
  { description: "Install new drywall in the basement after a leak.", skills: ["drywall repair", "leak repair"] },
  { description: "Install hardwood flooring in the living room and hallway.", skills: ["flooring installation", "carpentry"] },
  { description: "Replace an old heating system with a new efficient model.", skills: ["heating systems", "hvac"] },
  { description: "Fix a leaking pipe under the kitchen sink.", skills: ["plumbing", "leak repair", "pipe fitting"] },
  { description: "Install new LED lights throughout the house.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the entire house interior in neutral colors.", skills: ["painting"] },
  { description: "Replace the water heater with a more efficient model.", skills: ["water heater installation", "plumbing"] },
  { description: "Rewire the entire house for modern electrical standards.", skills: ["wiring", "electrical"] },
  { description: "Install a new ventilation system in the attic.", skills: ["ventilation", "hvac"] },
  { description: "Refrigerator is not cooling properly, need repair.", skills: ["refrigeration", "hvac"] },
  { description: "Install new cabinets and flooring in the bathroom.", skills: ["cabinet making", "flooring installation", "carpentry"] },
  { description: "Circuit breaker keeps tripping, need inspection and repair.", skills: ["circuit repair", "electrical"] },
  { description: "Patch and repaint drywall after repairing a leak.", skills: ["drywall repair", "painting", "leak repair"] },
  { description: "Install underfloor heating system in the living room.", skills: ["flooring installation", "heating systems"] },
  { description: "Need pipe fitting for new bathroom plumbing installation.", skills: ["pipe fitting", "plumbing"] },
  { description: "Need to replace old air conditioning filters.", skills: ["air conditioning"] },
  { description: "Boiler is leaking water, urgent repair needed.", skills: ["boiler repair", "leak repair"] },
  { description: "Custom bookshelf construction required in the study.", skills: ["cabinet making", "carpentry"] },
  { description: "Electrical outlet in kitchen not working, needs fixing.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall repair needed after plumbing work in bathroom.", skills: ["drywall repair", "plumbing"] },
  { description: "Install new carpet in bedrooms and hallway.", skills: ["flooring installation"] },
  { description: "Heating system maintenance needed before winter.", skills: ["heating systems", "hvac"] },
  { description: "Ventilation system not functioning, needs inspection.", skills: ["ventilation", "hvac"] },
  { description: "Replace old fluorescent lighting with modern LEDs.", skills: ["lighting installation", "electrical"] },
  { description: "Water heater making noise, might need replacement.", skills: ["water heater installation", "plumbing"] },
  { description: "Garage rewiring needed for new workshop setup.", skills: ["wiring", "electrical"] },
  { description: "Kitchen faucet leaking, repair or replace needed.", skills: ["plumbing", "leak repair"] },
  { description: "Install new cooling system in office space.", skills: ["air conditioning", "hvac"] },
  { description: "New pantry cabinets required for kitchen remodel.", skills: ["cabinet making", "carpentry"] },
  { description: "Living room ceiling fan installation required.", skills: ["lighting installation", "electrical"] },
  { description: "Repair cracks and repaint walls in dining room.", skills: ["drywall repair", "painting"] },
  { description: "Repair heating system before it gets too cold.", skills: ["heating systems", "boiler repair"] },
  { description: "Install new exhaust fan in the bathroom.", skills: ["ventilation", "electrical"] },
  { description: "Install hardwood flooring in the master bedroom.", skills: ["flooring installation", "carpentry"] },
  { description: "Inspect and repair faulty circuit in basement.", skills: ["circuit repair", "electrical"] },
  { description: "Refrigerator not cooling, needs immediate repair.", skills: ["refrigeration"] },
  { description: "Repair leaking pipes behind kitchen walls.", skills: ["pipe fitting", "leak repair", "plumbing"] },
  { description: "Replace outdated wiring throughout the house.", skills: ["wiring", "electrical"] },
  { description: "Install central air conditioning in new home.", skills: ["air conditioning", "hvac"] },
  { description: "Paint entire exterior of the house.", skills: ["painting"] },
  { description: "Install custom cabinetry in home office.", skills: ["cabinet making", "carpentry"] },
  { description: "Electrical issues causing frequent power outages.", skills: ["electrical", "circuit repair"] },
  { description: "Bathroom sink clogged, possible pipe repair needed.", skills: ["plumbing", "pipe fitting"] },
  { description: "Fix drywall cracks and repaint living room.", skills: ["drywall repair", "painting"] },
  { description: "Install new tiles and underfloor heating in bathroom.", skills: ["flooring installation", "heating systems"] },
  { description: "Replace broken water heater in the basement.", skills: ["water heater installation", "plumbing"] },
  { description: "Ventilation system needs upgrade in the attic.", skills: ["ventilation", "hvac"] },
  { description: "Repair faulty wiring in the kitchen area.", skills: ["wiring", "electrical"] },
  { description: "Install ceiling lights in the hallway.", skills: ["lighting installation", "electrical"] },
  { description: "Refrigerator making loud noises, possible motor issue.", skills: ["refrigeration"] },
  { description: "Repair loose cabinet doors in the kitchen.", skills: ["cabinet making", "carpentry"] },
  { description: "Repaint all rooms with new color scheme.", skills: ["painting"] },
  { description: "Fix electrical short circuit in garage.", skills: ["circuit repair", "electrical"] },
  { description: "Install new HVAC system in the office.", skills: ["hvac", "ventilation", "heating systems"] },
  { description: "Inspect and repair boiler before winter season.", skills: ["boiler repair", "heating systems"] },
  { description: "Install laminate flooring in the dining room.", skills: ["flooring installation"] },
  { description: "Replace damaged pipes in the laundry room.", skills: ["pipe fitting", "plumbing"] },
  { description: "Fix drywall holes after electrical work.", skills: ["drywall repair", "electrical"] },
  { description: "Replace old light fixtures with energy-efficient LEDs.", skills: ["lighting installation"] },
  { description: "HVAC system making noise, needs repair.", skills: ["hvac", "ventilation"] },
  { description: "Air conditioning unit blowing warm air, needs service.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler pilot light won't stay lit, urgent repair needed.", skills: ["boiler repair", "heating systems"] },
  { description: "Custom cabinets for the bathroom vanity required.", skills: ["cabinet making", "carpentry"] },
  { description: "Electrical wiring upgrade needed for safety compliance.", skills: ["wiring", "electrical"] },
  { description: "Repair water-damaged drywall in the laundry room.", skills: ["drywall repair", "leak repair"] },
  { description: "Install new vinyl flooring in the kitchen.", skills: ["flooring installation"] },
  { description: "Heating system thermostat malfunctioning, needs fixing.", skills: ["heating systems", "hvac"] },
  { description: "Ventilation duct cleaning and inspection required.", skills: ["ventilation", "hvac"] },
  { description: "Install new pendant lighting in the dining area.", skills: ["lighting installation", "electrical"] },
  { description: "Replace malfunctioning water heater with a tankless model.", skills: ["water heater installation", "plumbing"] },
  { description: "Basement requires complete electrical rewiring.", skills: ["wiring", "electrical"] },
  { description: "Fix leaking shower faucet in the master bathroom.", skills: ["plumbing", "leak repair"] },
  { description: "Central air conditioning system needs a tune-up.", skills: ["air conditioning", "hvac"] },
  { description: "Built-in closet cabinet installation in the master bedroom.", skills: ["cabinet making", "carpentry"] },
  { description: "Install recessed lighting in the living room ceiling.", skills: ["lighting installation", "electrical"] },
  { description: "Repair and repaint drywall in the kids' playroom.", skills: ["drywall repair", "painting"] },
  { description: "Heating system not distributing heat evenly, needs inspection.", skills: ["heating systems", "boiler repair"] },
  { description: "Upgrade bathroom ventilation fan for better airflow.", skills: ["ventilation", "electrical"] },
  { description: "Replace old carpet with laminate flooring in the office.", skills: ["flooring installation"] },
  { description: "Circuit breaker constantly tripping, needs professional repair.", skills: ["circuit repair", "electrical"] },
  { description: "Refrigerator door seal broken, needs replacement.", skills: ["refrigeration"] },
  { description: "Repair leaky pipe in the basement ceiling.", skills: ["pipe fitting", "leak repair", "plumbing"] },
  { description: "Upgrade house wiring to handle new electrical load.", skills: ["wiring", "electrical"] },
  { description: "Install smart thermostat for efficient heating and cooling.", skills: ["hvac", "heating systems"] },
  { description: "Paint exterior siding and trim for a fresh look.", skills: ["painting"] },
  { description: "Custom shelving unit needed in the garage.", skills: ["cabinet making", "carpentry"] },
  { description: "Electrical outlet sparking, urgent repair needed.", skills: ["electrical", "circuit repair"] },
  { description: "Fix slow drain in the kitchen sink.", skills: ["plumbing", "pipe fitting"] },
  { description: "Patch and paint drywall in the guest bedroom.", skills: ["drywall repair", "painting"] },
  { description: "Install radiant floor heating in the bathroom.", skills: ["flooring installation", "heating systems"] },
  { description: "Replace old water heater with a high-efficiency model.", skills: ["water heater installation", "plumbing"] },
  { description: "Install new ventilation system in the kitchen.", skills: ["ventilation", "hvac"] },
  { description: "Fix loose wiring connections in the attic.", skills: ["wiring", "electrical"] },
  { description: "Install dimmable lighting in the home theater.", skills: ["lighting installation", "electrical"] },
  { description: "Refrigerator ice maker not working, needs repair.", skills: ["refrigeration"] },
  { description: "Repair warped kitchen cabinet doors.", skills: ["cabinet making", "carpentry"] },
  { description: "Repaint entire basement after water damage repair.", skills: ["painting", "drywall repair"] },
  { description: "Fix electrical short in the outdoor lighting.", skills: ["circuit repair", "electrical"] },
  { description: "Install new HVAC unit for improved energy efficiency.", skills: ["hvac", "heating systems"] },
  { description: "Inspect and service boiler before the cold season.", skills: ["boiler repair", "heating systems"] },
  { description: "Install bamboo flooring in the living room.", skills: ["flooring installation"] },
  { description: "Repair leaking pipes in the crawl space.", skills: ["pipe fitting", "plumbing"] },
  { description: "Replace damaged drywall in the hallway.", skills: ["drywall repair"] },
  { description: "Upgrade to smart LED lighting throughout the house.", skills: ["lighting installation", "electrical"] },
  { description: "Air conditioning compressor making noise, needs attention.", skills: ["air conditioning", "hvac"] },
  { description: "Air conditioning unit not turning on, requires urgent repair.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler losing pressure, needs inspection and repair.", skills: ["boiler repair", "heating systems"] },
  { description: "Custom cabinetry needed for the new kitchen island.", skills: ["cabinet making", "carpentry"] },
  { description: "Electrical panel upgrade required to support new appliances.", skills: ["wiring", "electrical"] },
  { description: "Drywall repair needed after removing old wall fixtures.", skills: ["drywall repair"] },
  { description: "Install new laminate flooring in the basement.", skills: ["flooring installation"] },
  { description: "Heating system blowing cold air, requires immediate attention.", skills: ["heating systems", "hvac"] },
  { description: "Upgrade ventilation system in the basement for better airflow.", skills: ["ventilation", "hvac"] },
  { description: "Install track lighting in the art studio.", skills: ["lighting installation", "electrical"] },
  { description: "Replace old tank water heater with a tankless version.", skills: ["water heater installation", "plumbing"] },
  { description: "Rewire the garage for additional outlets and lighting.", skills: ["wiring", "electrical"] },
  { description: "Fix dripping faucet in the bathroom sink.", skills: ["plumbing", "leak repair"] },
  { description: "Air conditioning ductwork needs sealing to prevent leaks.", skills: ["air conditioning", "hvac"] },
  { description: "Built-in bookcases needed for the home library.", skills: ["cabinet making", "carpentry"] },
  { description: "Install chandelier in the dining room.", skills: ["lighting installation", "electrical"] },
  { description: "Patch and repaint drywall after removing old wallpaper.", skills: ["drywall repair", "painting"] },
  { description: "Heating system making a clunking noise, needs inspection.", skills: ["heating systems", "boiler repair"] },
  { description: "Install new ventilation system in the attic to prevent moisture buildup.", skills: ["ventilation", "hvac"] },
  { description: "Replace carpet with hardwood flooring in the living room.", skills: ["flooring installation"] },
  { description: "Repair faulty circuit causing lights to flicker.", skills: ["circuit repair", "electrical"] },
  { description: "Freezer compartment in refrigerator not freezing, needs repair.", skills: ["refrigeration"] },
  { description: "Replace corroded pipes in the kitchen.", skills: ["pipe fitting", "plumbing"] },
  { description: "Install new wiring for a home theater system.", skills: ["wiring", "electrical"] },
  { description: "Paint exterior doors and shutters for a refreshed look.", skills: ["painting"] },
  { description: "Custom closet installation needed in the master bedroom.", skills: ["cabinet making", "carpentry"] },
  { description: "Repair electrical outlet that keeps sparking.", skills: ["electrical", "circuit repair"] },
  { description: "Unclog slow-draining bathtub in the guest bathroom.", skills: ["plumbing", "pipe fitting"] },
  { description: "Fix cracks in drywall before painting.", skills: ["drywall repair", "painting"] },
  { description: "Install heated flooring in the kitchen for added comfort.", skills: ["flooring installation", "heating systems"] },
  { description: "Replace leaking water heater in the utility room.", skills: ["water heater installation", "plumbing"] },
  { description: "Improve ventilation in the bathroom to prevent mold.", skills: ["ventilation", "electrical"] },
  { description: "Fix wiring issues in the ceiling fan.", skills: ["wiring", "electrical"] },
  { description: "Install dimmer switches for the living room lights.", skills: ["lighting installation", "electrical"] },
  { description: "Refrigerator compressor malfunctioning, requires repair.", skills: ["refrigeration"] },
  { description: "Repair broken cabinet hinges in the kitchen.", skills: ["cabinet making", "carpentry"] },
  { description: "Repaint interior walls with a new color scheme.", skills: ["painting"] },
  { description: "Fix electrical short circuit in the basement.", skills: ["circuit repair", "electrical"] },
  { description: "Install new HVAC system in the renovated space.", skills: ["hvac", "ventilation", "heating systems"] },
  { description: "Service boiler to improve efficiency before winter.", skills: ["boiler repair", "heating systems"] },
  { description: "Install luxury vinyl flooring in the laundry room.", skills: ["flooring installation"] },
  { description: "Repair leaking water pipes in the bathroom wall.", skills: ["pipe fitting", "plumbing"] },
  { description: "Replace damaged drywall in the home office.", skills: ["drywall repair"] },
  { description: "Upgrade lighting in the kitchen to under-cabinet LEDs.", skills: ["lighting installation", "electrical"] },
  { description: "Air conditioning system needs refrigerant recharge.", skills: ["air conditioning", "hvac"] },
  { description: "Air conditioning unit leaking water, needs urgent repair.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler not heating up water, requires immediate attention.", skills: ["boiler repair", "heating systems"] },
  { description: "Custom-built storage cabinets needed for the garage.", skills: ["cabinet making", "carpentry"] },
  { description: "Upgrade home electrical system to support new solar panels.", skills: ["wiring", "electrical"] },
  { description: "Repair drywall damage from recent water leak.", skills: ["drywall repair", "leak repair"] },
  { description: "Install new hardwood flooring in the dining room.", skills: ["flooring installation"] },
  { description: "Heating system short-cycling, needs inspection.", skills: ["heating systems", "hvac"] },
  { description: "Install new ventilation system in the bathroom to improve airflow.", skills: ["ventilation", "hvac"] },
  { description: "Replace outdated lighting fixtures in the hallway.", skills: ["lighting installation", "electrical"] },
  { description: "Install new energy-efficient water heater in the basement.", skills: ["water heater installation", "plumbing"] },
  { description: "Rewire kitchen for additional outlets and appliances.", skills: ["wiring", "electrical"] },
  { description: "Fix persistent leak under the kitchen sink.", skills: ["plumbing", "leak repair"] },
  { description: "Air conditioning unit freezing up, needs repair.", skills: ["air conditioning", "hvac"] },
  { description: "Install custom cabinets in the walk-in closet.", skills: ["cabinet making", "carpentry"] },
  { description: "Install outdoor security lighting around the property.", skills: ["lighting installation", "electrical"] },
  { description: "Repair drywall holes left by removed shelving.", skills: ["drywall repair"] },
  { description: "Heating system requires new thermostat installation.", skills: ["heating systems", "electrical"] },
  { description: "Install new attic ventilation to reduce heat buildup.", skills: ["ventilation", "hvac"] },
  { description: "Replace old carpet with engineered wood flooring.", skills: ["flooring installation"] },
  { description: "Fix circuit breaker that keeps tripping.", skills: ["circuit repair", "electrical"] },
  { description: "Refrigerator not cooling evenly, needs professional repair.", skills: ["refrigeration"] },
  { description: "Replace broken pipe in the basement bathroom.", skills: ["pipe fitting", "plumbing"] },
  { description: "Install new wiring for the outdoor kitchen area.", skills: ["wiring", "electrical"] },
  { description: "Repaint kitchen cabinets for a modern look.", skills: ["painting", "cabinet making"] },
  { description: "Fix loose electrical outlet in the living room.", skills: ["electrical", "circuit repair"] },
  { description: "Clear clogged drain in the laundry room.", skills: ["plumbing", "pipe fitting"] },
  { description: "Repair drywall cracks in the hallway ceiling.", skills: ["drywall repair"] },
  { description: "Install underfloor heating in the master bathroom.", skills: ["flooring installation", "heating systems"] },
  { description: "Replace old water heater with a high-capacity model.", skills: ["water heater installation", "plumbing"] },
  { description: "Improve ventilation in the garage to reduce fumes.", skills: ["ventilation", "hvac"] },
  { description: "Fix wiring issues with the outdoor lighting system.", skills: ["wiring", "electrical"] },
  { description: "Install track lighting in the home office.", skills: ["lighting installation", "electrical"] },
  { description: "Refrigerator making loud humming noise, needs repair.", skills: ["refrigeration"] },
  { description: "Repair and refinish damaged kitchen cabinets.", skills: ["cabinet making", "carpentry"] },
  { description: "Repaint exterior trim and doors for curb appeal.", skills: ["painting"] },
  { description: "Repair electrical short in the attic lighting.", skills: ["circuit repair", "electrical"] },
  { description: "Install high-efficiency HVAC system in the entire house.", skills: ["hvac", "heating systems", "ventilation"] },
  { description: "Inspect and service boiler for annual maintenance.", skills: ["boiler repair", "heating systems"] },
  { description: "Install vinyl plank flooring in the mudroom.", skills: ["flooring installation"] },
  { description: "Replace leaking pipe joints in the crawl space.", skills: ["pipe fitting", "plumbing"] },
  { description: "Patch and repaint damaged drywall in the guest room.", skills: ["drywall repair", "painting"] },
  { description: "Upgrade lighting in the bathroom to brighter LED fixtures.", skills: ["lighting installation", "electrical"] },
  { description: "Air conditioning unit needs new condenser coils.", skills: ["air conditioning", "hvac"] },
  { description: "The central air conditioning system is not cooling efficiently and seems to be leaking water. It requires a thorough inspection and repair.", skills: [" air conditioning", "leak repair", "hvac"] },
  { description: "The boiler is making unusual noises and the radiators aren't heating up properly. Immediate repair is needed to avoid further damage.", skills: [" boiler repair", "heating systems"] },
  { description: "We need custom-built cabinets for the new kitchen island, along with some finishing carpentry work to match the existing décor.", skills: [" cabinet making", "carpentry"] },
  { description: "Several electrical outlets in the living room are not working, and the circuit breaker keeps tripping. This could be a wiring issue that needs urgent attention.", skills: [" electrical", "circuit repair", "wiring"] },
  { description: "After recent plumbing work, the drywall in the bathroom has been damaged and needs to be repaired and repainted.", skills: [" drywall repair", "plumbing", "painting"] },
  { description: "We're looking to install new hardwood flooring in the living room, but also need assistance with baseboard installation and carpentry.", skills: [" flooring installation", "carpentry"] },
  { description: "The heating system is not distributing heat evenly across the house, and some rooms are significantly colder than others. A complete system check is necessary.", skills: [" heating systems", "hvac"] },
  { description: "The ventilation system in the attic isn't working properly, leading to excess humidity and mold growth. This needs to be addressed quickly.", skills: [" ventilation", "hvac"] },
  { description: "We need to replace the existing lighting in the kitchen with energy-efficient LED lights, and also install dimmable switches.", skills: [" lighting installation", "electrical"] },
  { description: "The water heater is not producing enough hot water, and it seems to be nearing the end of its life. Replacement and installation of a new unit are required.", skills: [" water heater installation", "plumbing"] },
  { description: "The garage requires rewiring to support new power tools and additional lighting, ensuring everything meets current electrical codes.", skills: [" wiring", "electrical", "lighting installation"] },
  { description: "There's a persistent leak under the bathroom sink that we've been unable to fix ourselves. It may require new pipe fitting and plumbing repairs.", skills: [" leak repair", "pipe fitting", "plumbing"] },
  { description: "The air conditioning unit is cycling on and off frequently, which might be due to a problem with the HVAC system. A technician needs to inspect and resolve the issue.", skills: [" air conditioning", "hvac"] },
  { description: "We'd like to have custom-built shelving units installed in the study, with additional carpentry work to ensure they fit perfectly with the existing furniture.", skills: [" cabinet making", "carpentry"] },
  { description: "The recessed lighting in the living room is flickering, possibly due to a circuit issue. This needs to be checked and repaired.", skills: [" lighting installation", "circuit repair", "electrical"] },
  { description: "The drywall in the basement has developed cracks and some areas are bulging, likely due to moisture. Repairs are necessary before it gets worse.", skills: [" drywall repair", "leak repair"] },
  { description: "We want to replace the old carpet in the bedrooms with new laminate flooring, and also need help with underlayment and trim installation.", skills: [" flooring installation", "carpentry"] },
  { description: "The heating system seems to be struggling to maintain the set temperature, and the boiler pressure is fluctuating. It may require both heating and boiler repair.", skills: [" heating systems", "boiler repair", "hvac"] },
  { description: "The ventilation ducts in the house appear to be clogged, causing reduced airflow. They need to be cleaned and possibly reconfigured for better efficiency.", skills: [" ventilation", "hvac"] },
  { description: "We're planning to repaint the entire house interior, but first, some areas of the drywall need to be repaired where there are holes and cracks.", skills: [" painting", "drywall repair"] },
  { description: "The refrigerator is not cooling properly, and there seems to be a problem with the compressor. This requires immediate repair to prevent food spoilage.", skills: [" refrigeration"] },
  { description: "We're interested in having heated flooring installed in the bathroom, along with new tile flooring. This might involve both flooring and heating system work.", skills: [" flooring installation", "heating systems"] },
  { description: "The kitchen faucet is leaking and there may be an issue with the pipe fittings under the sink. Professional plumbing services are needed.", skills: [" leak repair", "pipe fitting", "plumbing"] },
  { description: "Several rooms in the house have old wiring that needs to be replaced to support modern electrical loads and improve safety.", skills: [" wiring", "electrical"] },
  { description: "The air conditioning system is blowing warm air and may need a refrigerant recharge or other repairs to the HVAC system.", skills: [" air conditioning", "hvac", "refrigeration"] },
  { description: "The air conditioning system is making a loud, rattling noise, and the airflow seems weaker than usual. It may require both mechanical and HVAC system repairs.", skills: [" air conditioning", "hvac"] },
  { description: "Our boiler is leaking water and not maintaining consistent pressure. We need an urgent inspection and repair to avoid a complete breakdown.", skills: [" boiler repair", "leak repair", "heating systems"] },
  { description: "We need custom cabinetry for our walk-in closet, along with some detailed carpentry work to match the existing woodwork in the bedroom.", skills: [" cabinet making", "carpentry"] },
  { description: "The circuit breaker in the garage trips every time we use multiple power tools. We suspect it might need an upgrade or a wiring inspection.", skills: [" circuit repair", "electrical", "wiring"] },
  { description: "There are significant holes and cracks in the drywall of the living room, likely from settling. We need these repaired and then the entire room repainted.", skills: [" drywall repair", "painting"] },
  { description: "We want to install new tile flooring in the kitchen, including underlayment and proper sealing to prevent moisture damage.", skills: [" flooring installation"] },
  { description: "The heating system is emitting a strange odor when turned on, and some radiators aren't heating up properly. A thorough inspection is necessary.", skills: [" heating systems", "hvac"] },
  { description: "Our home's ventilation system is inadequate, leading to stuffy rooms and condensation on the windows. We need to upgrade the system.", skills: [" ventilation", "hvac"] },
  { description: "We're planning to upgrade all the lighting in the house to smart LEDs, which will require new installations and possibly rewiring.", skills: [" lighting installation", "wiring", "electrical"] },
  { description: "The water heater is over 10 years old and not heating water efficiently. We're looking to replace it with a more energy-efficient model.", skills: [" water heater installation", "plumbing"] },
  { description: "The basement needs to be rewired to accommodate a new home theater system and additional lighting fixtures.", skills: [" wiring", "electrical"] },
  { description: "There's a leak in the kitchen ceiling, possibly from a pipe in the floor above. It requires immediate plumbing and leak repair.", skills: [" leak repair", "pipe fitting", "plumbing"] },
  { description: "The air conditioning unit is frequently turning on and off, and the temperature isn't consistent. This could be a thermostat or HVAC issue.", skills: [" air conditioning", "hvac"] },
  { description: "We'd like to add built-in bookshelves to our living room, with custom carpentry work to ensure they fit the space perfectly.", skills: [" cabinet making", "carpentry"] },
  { description: "Several of our ceiling lights have stopped working, and it seems to be an issue with the circuit. An electrician is needed to diagnose and fix the problem.", skills: [" lighting installation", "circuit repair", "electrical"] },
  { description: "The drywall in the hallway is showing signs of water damage, and we need to have it repaired before repainting the walls.", skills: [" drywall repair", "leak repair", "painting"] },
  { description: "We want to replace the current vinyl flooring in the kitchen with ceramic tiles, including proper leveling and sealing of the subfloor.", skills: [" flooring installation"] },
  { description: "The heating system isn't responding to the thermostat, and we're noticing uneven heating throughout the house. It may need a complete system check.", skills: [" heating systems", "hvac", "electrical"] },
  { description: "Our attic ventilation is poor, causing the space to get extremely hot in the summer. We need a new ventilation system installed.", skills: [" ventilation", "hvac"] },
  { description: "The entire interior of the house needs to be repainted, but there are several areas where the drywall is damaged and needs repair first.", skills: [" painting", "drywall repair"] },
  { description: "The refrigerator isn't maintaining a consistent temperature, and food is spoiling quickly. This needs to be repaired immediately.", skills: [" refrigeration"] },
  { description: "We are planning to install heated floors in the bathroom, along with new tiles. This project will involve both flooring and heating system work.", skills: [" flooring installation", "heating systems"] },
  { description: "The plumbing in the basement bathroom is causing slow drains and occasional leaks. It may need a combination of pipe fitting and repair work.", skills: [" pipe fitting", "plumbing", "leak repair"] },
  { description: "The old wiring in our house is causing frequent power surges. We need a complete rewiring to bring the electrical system up to code.", skills: [" wiring", "electrical"] },
  { description: "The air conditioning unit is not cooling the house as it should, and there seems to be an issue with the refrigerant levels. A thorough inspection and repair are needed.", skills: [" air conditioning", "hvac", "refrigeration"] },
  { description: "The air conditioning system is only cooling certain rooms, and there's a musty odor when it's running. It likely needs both HVAC maintenance and a duct cleaning.", skills: [" air conditioning", "hvac", "ventilation"] },
  { description: "The boiler has stopped working entirely, leaving us without hot water or heating. We need an emergency repair to get it up and running again.", skills: [" boiler repair", "heating systems"] },
  { description: "We want to add custom cabinets and shelving in the laundry room to maximize storage space, with additional carpentry work to match the existing decor.", skills: [" cabinet making", "carpentry"] },
  { description: "The circuit breaker panel is outdated and has difficulty handling our current electrical load. We need it replaced along with an upgrade to the home's wiring.", skills: [" circuit repair", "wiring", "electrical"] },
  { description: "Water damage from a roof leak has caused the drywall in the guest bedroom to bubble and crack. It needs to be repaired and repainted.", skills: [" drywall repair", "leak repair", "painting"] },
  { description: "We're looking to install bamboo flooring in the dining room, including the removal of the old carpet and preparation of the subfloor.", skills: [" flooring installation"] },
  { description: "The heating system is emitting a burning smell, and the airflow is weak in certain rooms. This could indicate a problem with the system that needs immediate attention.", skills: [" heating systems", "hvac"] },
  { description: "Our current ventilation system is not adequate for our kitchen renovation. We need a new system installed that can handle increased cooking activity.", skills: [" ventilation", "hvac"] },
  { description: "We're upgrading the lighting throughout the house with new fixtures and need professional installation, including the addition of dimmer switches in several rooms.", skills: [" lighting installation", "electrical"] },
  { description: "The water heater is struggling to maintain a consistent temperature, and we've noticed a slight leak at the base. It may need to be replaced.", skills: [" water heater installation", "plumbing", "leak repair"] },
  { description: "The attic needs to be rewired to support new insulation and lighting, ensuring everything is safe and up to code.", skills: [" wiring", "electrical"] },
  { description: "There’s a persistent leak in the shower that we haven't been able to fix. It may involve replacing some of the old pipe fittings.", skills: [" leak repair", "pipe fitting", "plumbing"] },
  { description: "Our air conditioning system is blowing warm air, and there's ice forming on the coils. This could be a sign of a refrigerant issue that needs fixing.", skills: [" air conditioning", "hvac", "refrigeration"] },
  { description: "We need custom bookshelves installed in the living room, with detailed carpentry work to blend seamlessly with the existing wood paneling.", skills: [" cabinet making", "carpentry"] },
  { description: "The outdoor lights are flickering, and a few have stopped working altogether. This may be due to a fault in the circuit that needs repair.", skills: [" lighting installation", "circuit repair", "electrical"] },
  { description: "The drywall in the stairwell has multiple cracks and dents from years of wear and tear. It needs to be patched up and then painted over.", skills: [" drywall repair", "painting"] },
  { description: "We’re planning to replace the old linoleum in the kitchen with tile flooring, including leveling the subfloor and ensuring proper grout sealing.", skills: [" flooring installation"] },
  { description: "The heating system is not maintaining the desired temperature, and the boiler pressure is fluctuating. Both the heating system and boiler need to be inspected.", skills: [" heating systems", "boiler repair", "hvac"] },
  { description: "Our ventilation system is outdated and not working efficiently, especially in the bathrooms. We need to install new exhaust fans and ducts.", skills: [" ventilation", "electrical"] },
  { description: "We want to repaint the entire house interior but need to fix several drywall imperfections first, including some areas with significant damage.", skills: [" painting", "drywall repair"] },
  { description: "The refrigerator is running but not cooling properly, and there seems to be a problem with the compressor or refrigerant levels. It needs urgent repair.", skills: [" refrigeration"] },
  { description: "We'd like to install heated floors in the sunroom, along with new wood flooring. This project will require both flooring and heating system expertise.", skills: [" flooring installation", "heating systems"] },
  { description: "The plumbing in the kitchen has been giving us trouble, with frequent clogs and a leaky faucet. We need professional pipe fitting and repair.", skills: [" pipe fitting", "plumbing", "leak repair"] },
  { description: "The house is in need of a complete rewiring to support modern electrical appliances, as the current wiring is outdated and causing frequent issues.", skills: [" wiring", "electrical"] },
  { description: "Our air conditioning system is leaking refrigerant and not cooling effectively. We need a full HVAC system check and potential refrigerant recharge.", skills: [" air conditioning", "hvac", "refrigeration"] },
  { description: "The air conditioning unit is not blowing cold air, and there's a strange noise coming from the outdoor unit.", skills: [" air conditioning", "hvac"] },
  { description: "Boiler pressure keeps dropping, and there's a small puddle forming under the unit.", skills: [" boiler repair", "leak repair", "heating systems"] },
  { description: "Custom cabinets needed for the kitchen remodel, with matching wood finishes and handles.", skills: [" cabinet making", "carpentry"] },
  { description: "The circuit breaker trips every time we use the microwave and toaster at the same time.", skills: [" circuit repair", "wiring", "electrical"] },
  { description: "Large cracks have appeared in the drywall near the living room windows after the recent storm.", skills: [" drywall repair"] },
  { description: "Need to upgrade the electrical panel to support a new home office setup with multiple computers.", skills: [" electrical", "wiring"] },
  { description: "Installing new hardwood flooring in the living room, including removal of old carpet and baseboards.", skills: [" flooring installation"] },
  { description: "Heating system isn't distributing heat evenly, and some rooms are much colder than others.", skills: [" heating systems", "hvac"] },
  { description: "There's a persistent leak in the basement, possibly from the main water line.", skills: [" leak repair", "plumbing"] },
  { description: "Replacing old light fixtures with modern, energy-efficient LED lights in the entire house.", skills: [" lighting installation", "electrical"] },
  { description: "Repainting the exterior of the house, including prepping and sanding down old paint.", skills: [" painting"] },
  { description: "Water heater isn't producing hot water consistently, especially during peak usage times.", skills: [" water heater installation", "plumbing"] },
  { description: "Ventilation system in the attic isn't working properly, leading to excessive heat buildup.", skills: [" ventilation", "hvac"] },
  { description: "Refrigerator is leaking water and not cooling properly, likely due to a malfunction in the compressor.", skills: [" refrigeration"] },
  { description: "The circuit for the kitchen outlets needs to be rewired due to frequent short circuits.", skills: [" circuit repair", "wiring", "electrical"] },
  { description: "Drywall in the bathroom is peeling and bubbling, likely due to moisture from a leak.", skills: [" drywall repair", "leak repair"] },
  { description: "Need new cabinets for the bathroom remodel, with additional carpentry work to install a custom vanity.", skills: [" cabinet making", "carpentry"] },
  { description: "The boiler isn't firing up, and the pilot light keeps going out.", skills: [" boiler repair", "heating systems"] },
  { description: "Installing new tile flooring in the kitchen, along with underfloor heating.", skills: [" flooring installation", "heating systems"] },
  { description: "Air conditioning unit is freezing up, and there's poor airflow in the upper floor rooms.", skills: [" air conditioning", "hvac"] },
  { description: "Upgrading the electrical wiring in the basement to add more outlets and support new appliances.", skills: [" wiring", "electrical"] },
  { description: "Persistent leak in the kitchen ceiling, likely due to a faulty pipe in the floor above.", skills: [" leak repair", "plumbing"] },
  { description: "Installing dimmable track lighting in the living room, with additional wiring work.", skills: [" lighting installation", "wiring", "electrical"] },
  { description: "Refinishing old hardwood floors in the dining room to remove scratches and stains.", skills: [" flooring installation"] },
  { description: "Replacing outdated ventilation system in the bathroom to reduce humidity and prevent mold.", skills: [" ventilation", "hvac"] },
  { description: "Refrigerator is making a loud humming noise and not cooling the freezer compartment properly.", skills: [" refrigeration"] },
  { description: "Air conditioning isn't cooling properly, and rooms feel humid.", skills: [" air conditioning", "hvac"] },
  { description: "Boiler isn't heating water and is making a loud banging noise.", skills: [" boiler repair", "heating systems"] },
  { description: "Need custom-built cabinets for a small home office.", skills: [" cabinet making", "carpentry"] },
  { description: "Breaker trips when using multiple kitchen appliances.", skills: [" circuit repair", "electrical"] },
  { description: "Cracked drywall in hallway needs patching and repainting.", skills: [" drywall repair", "painting"] },
  { description: "Need new outlets installed in the garage for power tools.", skills: [" electrical", "wiring"] },
  { description: "Installing laminate flooring in the bedroom.", skills: [" flooring installation"] },
  { description: "Heating system is slow to warm up the house.", skills: [" heating systems"] },
  { description: "Leak under the bathroom sink, needs urgent repair.", skills: [" leak repair", "plumbing"] },
  { description: "Installing new ceiling lights in the dining room.", skills: [" lighting installation", "electrical"] },
  { description: "Repainting the master bedroom a new color.", skills: [" painting"] },
  { description: "Water heater isn't providing enough hot water.", skills: [" water heater installation", "plumbing"] },
  { description: "Attic ventilation isn't working, causing high temperatures.", skills: [" ventilation", "hvac"] },
  { description: "Fridge isn't cooling properly, food is spoiling quickly.", skills: [" refrigeration"] },
  { description: "Electrical outlets in the basement are sparking.", skills: [" circuit repair", "electrical"] },
  { description: "Drywall near the window is damaged from moisture.", skills: [" drywall repair", "leak repair"] },
  { description: "Need new kitchen cabinets installed with soft-close hinges.", skills: [" cabinet making"] },
  { description: "Boiler is leaking and losing pressure.", skills: [" boiler repair", "leak repair"] },
  { description: "Installing hardwood floors in the living room.", skills: [" flooring installation"] },
  { description: "AC unit is making a rattling noise.", skills: [" air conditioning", "hvac"] },
  { description: "Rewiring old electrical system in the attic.", skills: [" wiring", "electrical"] },
  { description: "Fixing a leak in the kitchen ceiling.", skills: [" leak repair", "plumbing"] },
  { description: "Installing new track lighting in the kitchen.", skills: [" lighting installation"] },
  { description: "Sanding and staining old wood floors.", skills: [" flooring installation"] },
  { description: "Bathroom ventilation is poor, causing mold.", skills: [" ventilation", "hvac"] },
  { description: "Freezer isn't freezing food, fridge needs service.", skills: [" refrigeration"] },
  { description: "AC unit isn't cooling the house.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler isn't producing hot water.", skills: ["boiler repair", "heating systems"] },
  { description: "Need custom cabinets for the kitchen.", skills: ["cabinet making", "carpentry"] },
  { description: "Breaker trips when using the microwave.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall has holes and needs patching.", skills: ["drywall repair"] },
  { description: "Install new outlets in the living room.", skills: ["electrical", "wiring"] },
  { description: "Lay down new tile flooring in the bathroom.", skills: ["flooring installation"] },
  { description: "Heating system isn't warming up the house.", skills: ["heating systems", "hvac"] },
  { description: "Fix leak under the bathroom sink.", skills: ["leak repair", "plumbing"] },
  { description: "Install new ceiling fan with lights.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the entire house interior.", skills: ["painting"] },
  { description: "Water heater isn't working properly.", skills: ["water heater installation", "plumbing"] },
  { description: "Improve ventilation in the attic.", skills: ["ventilation", "hvac"] },
  { description: "Fridge isn't cooling properly.", skills: ["refrigeration"] },
  { description: "Garage outlets keep shorting out.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall near the window is cracked.", skills: ["drywall repair"] },
  { description: "Install custom-built bookcases.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler is leaking water.", skills: ["boiler repair", "leak repair"] },
  { description: "Replace old carpet with wood flooring.", skills: ["flooring installation"] },
  { description: "AC unit is making a loud noise.", skills: ["air conditioning", "hvac"] },
  { description: "Rewire the basement for new lighting.", skills: ["wiring", "electrical"] },
  { description: "Fix a ceiling leak in the bedroom.", skills: ["leak repair", "plumbing"] },
  { description: "Install new LED lighting in the kitchen.", skills: ["lighting installation", "electrical"] },
  { description: "Refinish hardwood floors in the hallway.", skills: ["flooring installation"] },
  { description: "Bathroom ventilation is poor, causing moisture.", skills: ["ventilation", "hvac"] },
  { description: "Refrigerator is leaking and not cooling.", skills: ["refrigeration"] },
  { description: "AC is blowing warm air.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler isn't turning on.", skills: ["boiler repair", "heating systems"] },
  { description: "Need new kitchen cabinets.", skills: ["cabinet making"] },
  { description: "Breaker keeps tripping.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall has a large crack.", skills: ["drywall repair"] },
  { description: "Install new outlets in the office.", skills: ["electrical", "wiring"] },
  { description: "Install vinyl flooring in the bathroom.", skills: ["flooring installation"] },
  { description: "Heater isn't working well.", skills: ["heating systems"] },
  { description: "Leak under the kitchen sink.", skills: ["leak repair", "plumbing"] },
  { description: "Install new ceiling lights.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the living room.", skills: ["painting"] },
  { description: "Water heater isn't heating.", skills: ["water heater installation", "plumbing"] },
  { description: "Attic needs better ventilation.", skills: ["ventilation", "hvac"] },
  { description: "Fridge is too warm.", skills: ["refrigeration"] },
  { description: "Outlets in the garage aren't working.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall is water-damaged.", skills: ["drywall repair", "leak repair"] },
  { description: "Install custom closet cabinets.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler is leaking.", skills: ["boiler repair", "leak repair"] },
  { description: "Replace carpet with wood flooring.", skills: ["flooring installation"] },
  { description: "AC unit is noisy.", skills: ["air conditioning", "hvac"] },
  { description: "Rewire old basement outlets.", skills: ["wiring", "electrical"] },
  { description: "Fix leak in bathroom ceiling.", skills: ["leak repair", "plumbing"] },
  { description: "Install dimmer switches.", skills: ["lighting installation", "electrical"] },
  { description: "Refinish hardwood floors.", skills: ["flooring installation"] },
  { description: "Bathroom fan isn't working.", skills: ["ventilation", "hvac"] },
  { description: "Fridge is leaking water.", skills: ["refrigeration"] },
  { description: "Air conditioning system is not cooling the upstairs rooms.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler keeps losing pressure.", skills: ["boiler repair", "heating systems"] },
  { description: "Need custom cabinets built for the laundry room.", skills: ["cabinet making"] },
  { description: "Circuit breaker trips when using the microwave.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall has holes from picture frames.", skills: ["drywall repair"] },
  { description: "Install additional outlets in the kitchen.", skills: ["electrical", "wiring"] },
  { description: "Install new tile flooring in the foyer.", skills: ["flooring installation"] },
  { description: "Heating system is making a rattling noise.", skills: ["heating systems"] },
  { description: "Fix leak under the bathroom sink.", skills: ["leak repair", "plumbing"] },
  { description: "Replace old light fixtures in the hallway.", skills: ["lighting installation", "electrical"] },
  { description: "Paint the exterior of the house.", skills: ["painting"] },
  { description: "Water heater pilot light won't stay lit.", skills: ["water heater installation", "plumbing"] },
  { description: "Attic ventilation needs improvement.", skills: ["ventilation", "hvac"] },
  { description: "Refrigerator isn't cooling properly.", skills: ["refrigeration"] },
  { description: "Electrical outlets in the kitchen aren't working.", skills: ["circuit repair", "electrical"] },
  { description: "Repair drywall in the basement.", skills: ["drywall repair"] },
  { description: "Build custom shelves in the garage.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler is making a strange noise.", skills: ["boiler repair", "heating systems"] },
  { description: "Install laminate flooring in the living room.", skills: ["flooring installation"] },
  { description: "Air conditioning unit is leaking water.", skills: ["air conditioning", "hvac"] },
  { description: "Upgrade wiring in the attic for new lighting.", skills: ["wiring", "electrical"] },
  { description: "Repair leak in the kitchen ceiling.", skills: ["leak repair", "plumbing"] },
  { description: "Install new recessed lighting in the living room.", skills: ["lighting installation", "electrical"] },
  { description: "Refinish and stain wood floors in the dining room.", skills: ["flooring installation"] },
  { description: "Bathroom ventilation fan is not powerful enough.", skills: ["ventilation", "hvac"] },
  { description: "Freezer isn't freezing food.", skills: ["refrigeration"] },
  { description: "AC unit is running constantly without cooling.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler won't start, no heat in the house.", skills: ["boiler repair", "heating systems"] },
  { description: "Need cabinets installed in the home office.", skills: ["cabinet making"] },
  { description: "Circuit keeps tripping when using hair dryer.", skills: ["circuit repair", "electrical"] },
  { description: "Patch small holes in drywall from screws.", skills: ["drywall repair"] },
  { description: "Add more electrical outlets in the basement.", skills: ["electrical", "wiring"] },
  { description: "Install new hardwood flooring in the bedroom.", skills: ["flooring installation"] },
  { description: "Heating system is only heating one floor.", skills: ["heating systems"] },
  { description: "Fix leaking pipe in the laundry room.", skills: ["leak repair", "plumbing"] },
  { description: "Replace old ceiling fan with new one.", skills: ["lighting installation", "electrical"] },
  { description: "Paint all walls in the master bedroom.", skills: ["painting"] },
  { description: "Water heater is making a loud noise.", skills: ["water heater installation", "plumbing"] },
  { description: "Attic ventilation system needs cleaning.", skills: ["ventilation", "hvac"] },
  { description: "Fridge isn't maintaining temperature.", skills: ["refrigeration"] },
  { description: "Electrical outlet in the bathroom is not working.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall is cracked near the door frame.", skills: ["drywall repair"] },
  { description: "Install custom cabinets in the garage.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler pressure is too high.", skills: ["boiler repair", "heating systems"] },
  { description: "Replace old carpet with laminate flooring.", skills: ["flooring installation"] },
  { description: "AC unit is short-cycling.", skills: ["air conditioning", "hvac"] },
  { description: "Rewire the kitchen for new appliances.", skills: ["wiring", "electrical"] },
  { description: "Fix ceiling leak from upstairs bathroom.", skills: ["leak repair", "plumbing"] },
  { description: "Install pendant lights over the kitchen island.", skills: ["lighting installation", "electrical"] },
  { description: "Sand and refinish wood floors in the hallway.", skills: ["flooring installation"] },
  { description: "Bathroom fan is making a loud noise.", skills: ["ventilation", "hvac"] },
  { description: "Refrigerator is freezing food in the fridge compartment.", skills: ["refrigeration"] },
  { description: "Air conditioning is only cooling part of the house.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler keeps shutting off unexpectedly.", skills: ["boiler repair", "heating systems"] },
  { description: "Build custom cabinets for the kitchen.", skills: ["cabinet making"] },
  { description: "Circuit breaker trips when using multiple devices.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall needs repair after plumbing work.", skills: ["drywall repair"] },
  { description: "Install more electrical outlets in the living room.", skills: ["electrical", "wiring"] },
  { description: "Install tile flooring in the kitchen.", skills: ["flooring installation"] },
  { description: "Heating system is not working efficiently.", skills: ["heating systems"] },
  { description: "Fix leak in the basement wall.", skills: ["leak repair", "plumbing"] },
  { description: "Replace track lighting with recessed lights.", skills: ["lighting installation", "electrical"] },
  { description: "Paint the trim and doors in the house.", skills: ["painting"] },
  { description: "Water heater is leaking at the base.", skills: ["water heater installation", "plumbing"] },
  { description: "Ventilation system in the attic needs repair.", skills: ["ventilation", "hvac"] },
  { description: "Freezer isn't making ice.", skills: ["refrigeration"] },
  { description: "AC unit is leaking refrigerant.", skills: ["air conditioning", "hvac", "refrigeration"] },
  { description: "Boiler is not heating the water properly.", skills: ["boiler repair", "heating systems"] },
  { description: "AC is blowing warm air and making a strange noise.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler pressure is low, and it's leaking water.", skills: ["boiler repair", "leak repair"] },
  { description: "Need custom-built kitchen cabinets and shelves.", skills: ["cabinet making", "carpentry"] },
  { description: "Circuit breaker trips when using multiple appliances.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall in the hallway has a large crack and needs repair.", skills: ["drywall repair"] },
  { description: "Install new outlets in the garage for power tools.", skills: ["electrical", "wiring"] },
  { description: "Need new laminate flooring installed in the bedroom.", skills: ["flooring installation"] },
  { description: "Heater isn't warming up the house evenly.", skills: ["heating systems", "hvac"] },
  { description: "Leak under the bathroom sink needs urgent repair.", skills: ["leak repair", "plumbing"] },
  { description: "Install new ceiling lights in the living room.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the entire interior of the house.", skills: ["painting"] },
  { description: "Water heater isn't producing hot water consistently.", skills: ["water heater installation", "plumbing"] },
  { description: "Ventilation system in attic isn't functioning properly.", skills: ["ventilation", "hvac"] },
  { description: "Fridge isn't cooling food properly.", skills: ["refrigeration"] },
  { description: "Outlets in the kitchen aren't working correctly.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall near the windows has water damage.", skills: ["drywall repair", "leak repair"] },
  { description: "Need custom cabinets for bathroom renovation.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler isn't firing up and pilot light won't stay lit.", skills: ["boiler repair", "heating systems"] },
  { description: "Install hardwood floors in the dining room.", skills: ["flooring installation"] },
  { description: "AC unit is making a loud rattling noise.", skills: ["air conditioning", "hvac"] },
  { description: "Rewiring old electrical system in the basement.", skills: ["wiring", "electrical"] },
  { description: "Fix a leak in the ceiling above the kitchen.", skills: ["leak repair", "plumbing"] },
  { description: "Install new dimmable LED lights in the kitchen.", skills: ["lighting installation", "electrical"] },
  { description: "Refinish hardwood floors in the living room.", skills: ["flooring installation"] },
  { description: "Bathroom ventilation fan isn't working properly.", skills: ["ventilation", "hvac"] },
  { description: "Fridge is leaking water onto the floor.", skills: ["refrigeration"] },
  { description: "AC isn't cooling the house efficiently.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler pressure keeps dropping and needs repair.", skills: ["boiler repair", "heating systems"] },
  { description: "Custom kitchen cabinets needed for remodel.", skills: ["cabinet making", "carpentry"] },
  { description: "Breaker trips when using microwave and toaster.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall in the hallway is cracked and peeling.", skills: ["drywall repair"] },
  { description: "Install new electrical outlets in the attic.", skills: ["electrical", "wiring"] },
  { description: "Need new tile flooring installed in the bathroom.", skills: ["flooring installation"] },
  { description: "Heating system is not distributing heat evenly.", skills: ["heating systems", "hvac"] },
  { description: "Leak in the basement needs immediate repair.", skills: ["leak repair", "plumbing"] },
  { description: "Install new track lighting in the bedroom.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the exterior of the house.", skills: ["painting"] },
  { description: "Water heater isn't providing enough hot water.", skills: ["water heater installation", "plumbing"] },
  { description: "Attic ventilation needs improvement to prevent heat.", skills: ["ventilation", "hvac"] },
  { description: "Refrigerator isn't keeping food cold enough.", skills: ["refrigeration"] },
  { description: "Outlets in the garage are not working properly.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall around windows is bubbling and cracking.", skills: ["drywall repair", "leak repair"] },
  { description: "Custom bathroom cabinets needed for remodel.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler isn't heating water properly.", skills: ["boiler repair", "heating systems"] },
  { description: "Install new hardwood floors in the bedroom.", skills: ["flooring installation"] },
  { description: "AC unit isn't blowing cold air.", skills: ["air conditioning", "hvac"] },
  { description: "Rewire old electrical system in the garage.", skills: ["wiring", "electrical"] },
  { description: "Fix leak in ceiling above the bathroom.", skills: ["leak repair", "plumbing"] },
  { description: "Install recessed lighting in the living room.", skills: ["lighting installation", "electrical"] },
  { description: "Sand and refinish old hardwood floors.", skills: ["flooring installation"] },
  { description: "Bathroom ventilation is poor and needs fixing.", skills: ["ventilation", "hvac"] },
  { description: "Fridge isn't freezing food properly.", skills: ["refrigeration"] },
  { description: "AC is leaking water and not cooling properly.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler is making a loud banging noise.", skills: ["boiler repair", "heating systems"] },
  { description: "Need custom cabinets for the laundry room.", skills: ["cabinet making"] },
  { description: "Circuit breaker needs replacement.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall in the ceiling is sagging.", skills: ["drywall repair"] },
  { description: "Install new electrical wiring for home office.", skills: ["wiring", "electrical"] },
  { description: "Replace carpet with wood flooring.", skills: ["flooring installation"] },
  { description: "Heater isn't warming the house properly.", skills: ["heating systems"] },
  { description: "Leak under kitchen sink needs repair.", skills: ["leak repair", "plumbing"] },
  { description: "Install ceiling fan with lighting.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the front door and shutters.", skills: ["painting"] },
  { description: "Water heater is leaking and needs replacement.", skills: ["water heater installation", "plumbing"] },
  { description: "Attic ventilation fan isn't working.", skills: ["ventilation", "hvac"] },
  { description: "Refrigerator is making a loud noise.", skills: ["refrigeration"] },
  { description: "Outlets in the bedroom aren't working.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall has multiple small cracks.", skills: ["drywall repair"] },
  { description: "Custom shelving for the living room needed.", skills: ["cabinet making", "carpentry"] },
  { description: "Boiler keeps losing pressure.", skills: ["boiler repair", "heating systems"] },
  { description: "Install new vinyl flooring in the kitchen.", skills: ["flooring installation"] },
  { description: "AC unit is not turning on at all.", skills: ["air conditioning", "hvac"] },
  { description: "Rewire the old electrical system in attic.", skills: ["wiring", "electrical"] },
  { description: "Fix leak in the ceiling above the living room.", skills: ["leak repair", "plumbing"] },
  { description: "Install track lighting in the hallway.", skills: ["lighting installation", "electrical"] },
  { description: "Refinish and stain hardwood floors.", skills: ["flooring installation"] },
  { description: "Bathroom fan isn't ventilating properly.", skills: ["ventilation", "hvac"] },
  { description: "Fridge is not cooling or freezing food.", skills: ["refrigeration"] },
  { description: "AC needs repair, it's blowing warm air.", skills: ["air conditioning", "hvac"] },
  { description: "Boiler is leaking water and making noise.", skills: ["boiler repair", "leak repair"] },
  { description: "Install custom cabinets in the pantry.", skills: ["cabinet making"] },
  { description: "Breaker trips frequently in the kitchen.", skills: ["circuit repair", "electrical"] },
  { description: "Drywall near the stairs is cracking.", skills: ["drywall repair"] },
  { description: "Install new electrical panel in basement.", skills: ["wiring", "electrical"] },
  { description: "Replace old flooring with new tiles.", skills: ["flooring installation"] },
  { description: "Heating system is blowing cold air.", skills: ["heating systems", "hvac"] },
  { description: "Leak in the shower needs fixing.", skills: ["leak repair", "plumbing"] },
  { description: "Install new recessed lighting in kitchen.", skills: ["lighting installation", "electrical"] },
  { description: "Repaint the kitchen and dining room.", skills: ["painting"] },
  { description: "Water heater isn't working at all.", skills: ["water heater installation"] },
]

exports.default = data;
